In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\ZAID AWAN\Desktop\practice csv.csv")
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Country,Product_Category,Product_Name,Unit_Price_USD,Quantity,Discount_Percent,Discount_Amount_USD,Shipping_Cost_USD,Tax_USD,Total_Amount_USD,Payment_Method,Order_Status,Customer_Rating
0,ORD-000001,2026-06-17 00:37:00,CUST-00439,Sana Butt,25,Male,Quetta,Pakistan,Clothing,Coffee Maker,464.43,4,20,371.54,0.0,118.89,1605.07,Mobile Wallet,Completed,2
1,ORD-000002,2025-04-03 12:30:00,CUST-02992,Zainab Shah,41,Male,Quetta,Pakistan,Groceries,Hair Dryer,483.01,4,0,0.00,0.0,154.56,2086.6,Credit Card,Completed,1
2,ORD-000003,2026-02-01 07:53:00,CUST-00411,Danish Hussain,67,Female,Faisalabad,Pakistan,Clothing,Coffee Maker,218.01,3,20,130.81,0.0,41.86,565.08,Debit Card,Returned,2
3,ORD-000004,2025-08-08 19:02:00,CUST-03824,Maha Raza,66,Female,Lahore,Pakistan,Books,Building Blocks,298.51,4,0,0.00,0.0,95.52,1289.56,Debit Card,Completed,2
4,ORD-000005,2026-06-12 07:08:00,CUST-02738,Bilal Ali,20,Male,Peshawar,Pakistan,Toys,Puzzle Set,50.26,4,0,0.00,0.0,16.08,217.12,Debit Card,Completed,2

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12250 entries, 0 to 12249
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             12250 non-null  str
 1   Order_Date           12250 non-null  str
 2   Customer_ID          12250 non-null  str
 3   Customer_Name        12185 non-null  str
 4   Age                  12165 non-null  str
 5   Gender               12250 non-null  str
 6   City                 12182 non-null  str
 7   Country              12250 non-null  str
 8   Product_Category     12185 non-null  str
 9   Product_Name         12250 non-null  str
 10  Unit_Price_USD       12183 non-null  str
 11  Quantity             12232 non-null  str
 12  Discount_Percent     12224 non-null  str
 13  Discount_Amount_USD  12250 non-null  float64
 14  Shipping_Cost_USD    12250 non-null  float64
 15  Tax_USD              12250 non-null  float64
 16  Total_Amount_USD     12236 non-null  str
 17  Payment_Method       12184 non-null  str
 18  Order_Status         12184 non-null  str
 19  Customer_Rating      12165 non-null  str
dtypes: float64(3), str(17)
memory usage: 1.9 MB

In [5]:
df.describe().round()

       Discount_Amount_USD  Shipping_Cost_USD  Tax_USD
count              12250.0            12250.0  12250.0
mean                  55.0                1.0     57.0
std                   84.0                3.0     44.0
min                    0.0                0.0      0.0
25%                    0.0                0.0     21.0
50%                   14.0                0.0     44.0
75%                   77.0                0.0     83.0
max                  496.0               15.0    200.0

In [6]:
df.isnull().sum()

Order_ID                0
Order_Date              0
Customer_ID             0
Customer_Name          65
Age                    85
Gender                  0
City                   68
Country                 0
Product_Category       65
Product_Name            0
Unit_Price_USD         67
Quantity               18
Discount_Percent       26
Discount_Amount_USD     0
Shipping_Cost_USD       0
Tax_USD                 0
Total_Amount_USD       14
Payment_Method         66
Order_Status           66
Customer_Rating        85
dtype: int64

In [7]:
df.shape

(12250, 20)

In [8]:
df[df.duplicated()].shape

(250, 20)

In [9]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Country,Product_Category,Product_Name,Unit_Price_USD,Quantity,Discount_Percent,Discount_Amount_USD,Shipping_Cost_USD,Tax_USD,Total_Amount_USD,Payment_Method,Order_Status,Customer_Rating
0,ORD-000001,2026-06-17 00:37:00,CUST-00439,Sana Butt,25,Male,Quetta,Pakistan,Clothing,Coffee Maker,464.43,4,20,371.54,0.0,118.89,1605.07,Mobile Wallet,Completed,2
1,ORD-000002,2025-04-03 12:30:00,CUST-02992,Zainab Shah,41,Male,Quetta,Pakistan,Groceries,Hair Dryer,483.01,4,0,0.00,0.0,154.56,2086.6,Credit Card,Completed,1
2,ORD-000003,2026-02-01 07:53:00,CUST-00411,Danish Hussain,67,Female,Faisalabad,Pakistan,Clothing,Coffee Maker,218.01,3,20,130.81,0.0,41.86,565.08,Debit Card,Returned,2
3,ORD-000004,2025-08-08 19:02:00,CUST-03824,Maha Raza,66,Female,Lahore,Pakistan,Books,Building Blocks,298.51,4,0,0.00,0.0,95.52,1289.56,Debit Card,Completed,2
4,ORD-000005,2026-06-12 07:08:00,CUST-02738,Bilal Ali,20,Male,Peshawar,Pakistan,Toys,Puzzle Set,50.26,4,0,0.00,0.0,16.08,217.12,Debit Card,Completed,2

In [10]:
df['Order_ID'].value_counts().head(10)

Order_ID
ORD-003766    3
ORD-005367    3
ORD-005650    3
ORD-006515    3
ORD-011250    3
ORD-000049    2
ORD-000059    2
ORD-000105    2
ORD-000127    2
ORD-000164    2
Name: count, dtype: int64

In [11]:
df[df['Order_ID']== 'ORD-003766']

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Country,Product_Category,Product_Name,Unit_Price_USD,Quantity,Discount_Percent,Discount_Amount_USD,Shipping_Cost_USD,Tax_USD,Total_Amount_USD,Payment_Method,Order_Status,Customer_Rating
3765,ORD-003766,2026-06-06 11:08:00,CUST-01961,Bilal Ali,32,Other,Faisalabad,Pakistan,Electronics,Cotton T-Shirt,148.11,5,0,0.0,0.0,59.24,799.79,Debit Card,Completed,1
12021,ORD-003766,2026-06-06 11:08:00,CUST-01961,Bilal Ali,32,Other,Faisalabad,Pakistan,Electronics,Cotton T-Shirt,148.11,5,0,0.0,0.0,59.24,799.79,Debit Card,Completed,1
12115,ORD-003766,2026-06-06 11:08:00,CUST-01961,Bilal Ali,32,Other,Faisalabad,Pakistan,Electronics,Cotton T-Shirt,148.11,5,0,0.0,0.0,59.24,799.79,Debit Card,Completed,1

In [12]:
for col in df.columns:
    if df[col].nunique() <20:
        print(col)
        print(df[col].value_counts())
        print('-'*50)

Gender
Gender
Other     4138
Male      4100
Female    4012
Name: count, dtype: int64
--------------------------------------------------
City
City
Multan        1325
Islamabad     1239
Faisalabad    1233
Sialkot       1231
Peshawar      1224
Rawalpindi    1211
Quetta        1208
Hyderabad     1188
Karachi       1172
Lahore        1151
Name: count, dtype: int64
--------------------------------------------------
Country
Country
Pakistan    12250
Name: count, dtype: int64
--------------------------------------------------
Product_Category
Product_Category
Beauty            1539
Clothing          1535
Sports            1531
Home & Kitchen    1530
Groceries         1523
Electronics       1522
Books             1512
Toys              1493
Name: count, dtype: int64
--------------------------------------------------
Product_Name
Product_Name
Yoga Mat                   817
Coffee Maker               788
Desk Lamp                  786
Denim Jeans                772
Smart Watch                769
Football                   768
Wireless Headphones        767
Hair Dryer                 765
Cotton T-Shirt             764
Data Analysis Guide        760
Building Blocks            759
Organic Tea Pack           758
Python Programming Book    757
Puzzle Set                 753
Snack Box                  748
Skin Care Set              719
Name: count, dtype: int64
--------------------------------------------------
Quantity
Quantity
4        2546
2        2444
3        2438
5        2407
1        2360
many       20
three      17
Name: count, dtype: int64
--------------------------------------------------
Discount_Percent
Discount_Percent
0              5217
5              1775
10             1740
20             1735
15             1726
ten percent      16
unknown          15
Name: count, dtype: int64
--------------------------------------------------
Payment_Method
Payment_Method
Credit Card         2472
Bank Transfer       2468
Debit Card          2424
Cash on Delivery    2416
Mobile Wallet       2404
Name: count, dtype: int64
--------------------------------------------------
Order_Status
Order_Status
Completed    6887
Cancelled    1791
Pending      1755
Returned     1751
Name: count, dtype: int64
--------------------------------------------------
Customer_Rating
Customer_Rating
2             2526
3             2502
1             2391
5             2358
4             2352
unknown         21
five stars      15
Name: count, dtype: int64
--------------------------------------------------

In [13]:
df.count()

Order_ID               12250
Order_Date             12250
Customer_ID            12250
Customer_Name          12185
Age                    12165
Gender                 12250
City                   12182
Country                12250
Product_Category       12185
Product_Name           12250
Unit_Price_USD         12183
Quantity               12232
Discount_Percent       12224
Discount_Amount_USD    12250
Shipping_Cost_USD      12250
Tax_USD                12250
Total_Amount_USD       12236
Payment_Method         12184
Order_Status           12184
Customer_Rating        12165
dtype: int64

In [14]:
df =df.drop_duplicates()

In [15]:
df.count()

Order_ID               12000
Order_Date             12000
Customer_ID            12000
Customer_Name          11935
Age                    11918
Gender                 12000
City                   11935
Country                12000
Product_Category       11935
Product_Name           12000
Unit_Price_USD         11936
Quantity               11982
Discount_Percent       11975
Discount_Amount_USD    12000
Shipping_Cost_USD      12000
Tax_USD                12000
Total_Amount_USD       11987
Payment_Method         11935
Order_Status           11935
Customer_Rating        11916
dtype: int64

In [16]:
df.columns = df.columns.str.strip()

In [17]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Country,Product_Category,Product_Name,Unit_Price_USD,Quantity,Discount_Percent,Discount_Amount_USD,Shipping_Cost_USD,Tax_USD,Total_Amount_USD,Payment_Method,Order_Status,Customer_Rating
0,ORD-000001,2026-06-17 00:37:00,CUST-00439,Sana Butt,25,Male,Quetta,Pakistan,Clothing,Coffee Maker,464.43,4,20,371.54,0.0,118.89,1605.07,Mobile Wallet,Completed,2
1,ORD-000002,2025-04-03 12:30:00,CUST-02992,Zainab Shah,41,Male,Quetta,Pakistan,Groceries,Hair Dryer,483.01,4,0,0.00,0.0,154.56,2086.6,Credit Card,Completed,1
2,ORD-000003,2026-02-01 07:53:00,CUST-00411,Danish Hussain,67,Female,Faisalabad,Pakistan,Clothing,Coffee Maker,218.01,3,20,130.81,0.0,41.86,565.08,Debit Card,Returned,2
3,ORD-000004,2025-08-08 19:02:00,CUST-03824,Maha Raza,66,Female,Lahore,Pakistan,Books,Building Blocks,298.51,4,0,0.00,0.0,95.52,1289.56,Debit Card,Completed,2
4,ORD-000005,2026-06-12 07:08:00,CUST-02738,Bilal Ali,20,Male,Peshawar,Pakistan,Toys,Puzzle Set,50.26,4,0,0.00,0.0,16.08,217.12,Debit Card,Completed,2

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             12000 non-null  str
 1   Order_Date           12000 non-null  str
 2   Customer_ID          12000 non-null  str
 3   Customer_Name        11935 non-null  str
 4   Age                  11918 non-null  str
 5   Gender               12000 non-null  str
 6   City                 11935 non-null  str
 7   Country              12000 non-null  str
 8   Product_Category     11935 non-null  str
 9   Product_Name         12000 non-null  str
 10  Unit_Price_USD       11936 non-null  str
 11  Quantity             11982 non-null  str
 12  Discount_Percent     11975 non-null  str
 13  Discount_Amount_USD  12000 non-null  float64
 14  Shipping_Cost_USD    12000 non-null  float64
 15  Tax_USD              12000 non-null  float64
 16  Total_Amount_USD     11987 non-null  str
 17  Payment_Method       11935 non-null  str
 18  Order_Status         11935 non-null  str
 19  Customer_Rating      11916 non-null  str
dtypes: float64(3), str(17)
memory usage: 1.8 MB

In [19]:
df = df.replace(r'^\s*$', pd.NA, regex=True)

In [20]:
df.isnull().sum()

Order_ID                0
Order_Date              0
Customer_ID             0
Customer_Name          65
Age                    82
Gender                  0
City                   65
Country                 0
Product_Category       65
Product_Name            0
Unit_Price_USD         64
Quantity               18
Discount_Percent       25
Discount_Amount_USD     0
Shipping_Cost_USD       0
Tax_USD                 0
Total_Amount_USD       13
Payment_Method         65
Order_Status           65
Customer_Rating        84
dtype: int64

In [21]:
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

In [22]:
text_cols = df.select_dtypes(include='object').columns
df[text_cols] =df[text_cols].fillna('Unknown')

C:\Users\ZAID AWAN\AppData\Local\Temp\ipykernel_512\1122391232.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include='object').columns

In [23]:
df.isnull().sum()

Order_ID               0
Order_Date             0
Customer_ID            0
Customer_Name          0
Age                    0
Gender                 0
City                   0
Country                0
Product_Category       0
Product_Name           0
Unit_Price_USD         0
Quantity               0
Discount_Percent       0
Discount_Amount_USD    0
Shipping_Cost_USD      0
Tax_USD                0
Total_Amount_USD       0
Payment_Method         0
Order_Status           0
Customer_Rating        0
dtype: int64